insert into User values(101,'Shambhavi','tech1');
insert into user values(102,'Suvrat','tech2');
insert into user values(103,'Diksha','tech3');
insert into user values(104,'Shubham','tech4');
insert into user values(105,'Janhvi','tech5');
insert into user values(106,'Shubham Arya','tech12');
insert into user values(107,'Samarth','tech6');
insert into user values(108,'Ayush','tech7');
insert into user values(109,'Shriya','tech8');
insert into user values(110,'Sumer','tech9');
insert into user values(111,'Divya','tech10');
insert into user values(112,'Avani','tech11');
insert into user values(113,'Nakul','tech13');
insert into user values(114,'Arshiya','tech14');
insert into user values(115,'Abhishek','tech15');